### ISSUE TITLE
Subprocess error in `kill_all_connections`

### ISSUE THREAD

**Issue by f-hafner** [ivory-tower-private-power/sirup#8]
Error: 
```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  
  File ".../sirup/utils.py", line 128, in kill_all_connections
    subprocess.run(kill_command, input=pwd.encode(), capture_output=True, check=True)
  File ".../env/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', '-S', 'kill', '-15', '2469678']' returned non-zero exit status 1.
```

Not sure how to reproduce and fix

**Comment by f-hafner** [comment]
the subprocess exits with code 1. unclear 1;  fixed in e312ee04cff3f3dee8e71343fc4a2abfdff028c4 by handling the exception and throwing a warning.
